---
title: "Dataset Description"
output:
  pdf_document: default
  html_notebook: default
---

# Imports
```{r}
library(fairmodels)
library(tidymodels)
library(rpart)
library(discrim)
source("../scripts/metrics_on_dataset.R")
```

# The Dataset
```{r}
df <- read_rds("../data/selection.rds")
df_test <- read_rds("../data/selection_test.rds")
head(df, 10)
```

## Characteristics
### Training dataset
```{r echo=FALSE}
print("Full dataset")
summary(df)
print("Test score SD, Rating SD")
print(c(sd(df$test_score), sd(df$rating)))

print("Accepted applicants")
summary(filter(df, accepted))
print("Test score SD, Rating SD")
print(c(sd(filter(df, accepted)$test_score), sd(filter(df, accepted)$rating)))

print("Not accepted applicants")
summary(filter(df, !accepted))
print("Test score SD, Rating SD")
print(c(sd(filter(df, !accepted)$test_score), sd(filter(df, !accepted)$rating)))

```
### Test dataset
```{r echo=FALSE}
summary(df_test)
print("Test score SD, Rating SD")
print(c(sd(df_test$test_score), sd(df_test$rating)))

```

# Metrics on the Dataset
```{r}
model <- decision_tree(mode = "classification")
results <- all_metrics(df, model, df_test)
print_all_metrics("Unmodified dataset", results)
```


