---
title: "Post-processing measures"
output:
  pdf_document: default
  html_notebook: default
---
# Imports
```{r}
library(fairmodels)
library(tidymodels)
library(rpart)
library(discrim)
source("../scripts/metrics_on_dataset.R")
```
## Data
```{r}
df <- read_rds("../data/selection.rds") %>%
  select(-gender, -rating) %>%
  mutate(accepted = as.factor(accepted))
```

# Naive Bayes ensamble
## Functions
```{r}
adjust_fit <- function(cutoffs, direction){
  if (direction == "up"){
    cutoffs["Non_Dutch"] <- cutoffs["Non_Dutch"] - 0.01
  } else if (direction == "down"){
    cutoffs["Dutch"] <- cutoffs["Dutch"] + 0.01
  }
  cutoffs
}

df_disc <- function(df){
  summary_true <- group_fairness(df, nationality, predicted)[[1]] %>%
    filter(predicted == "TRUE")
  max_val <- max(select(summary_true, perc))
  min_val <- min(select(summary_true, perc))
  
  list(disc = max_val - min_val, n = sum(select(summary_true, total)))
}

predictions <- function(df, fitted_models, cutoffs) {
  df_dutch <- filter(df, nationality == "Dutch")
  df_non_dutch <- filter(df, nationality != "Dutch")
  
  predictions_dutch <- predict(fitted_models[["Dutch"]], df_dutch, type="prob")[".pred_TRUE"]
  predictions_non_dutch <- predict(fitted_models[["Non_Dutch"]], df_non_dutch, type="prob")[".pred_TRUE"]
  
  df_dutch["predicted"] <- as.factor(predictions_dutch >= cutoffs["Dutch"])
  df_non_dutch["predicted"] <- as.factor(predictions_non_dutch >= cutoffs["Non_Dutch"])

  joined_df = bind_rows(df_dutch, df_non_dutch)
}

causal_discrimination_joined_model <- function(df, fitted_models, cutoffs) {
  pop_size <- nrow(df)
  
  df_dutch <- filter(df, nationality == "Dutch")
  df_non_dutch <- filter(df, nationality != "Dutch")
  
  predictions_dutch <- predict(fitted_models[["Dutch"]], df_dutch, type="prob")[".pred_TRUE"]
  inv_predictions_dutch <- predict(fitted_models[["Non_Dutch"]], df_dutch, type="prob")[".pred_TRUE"]

  predictions_non_dutch <- predict(fitted_models[["Non_Dutch"]], df_non_dutch, type="prob")[".pred_TRUE"]
  inv_predictions_non_dutch <- predict(fitted_models[["Dutch"]], df_non_dutch, type="prob")[".pred_TRUE"]
  
  df_dutch["predicted"] <- as.factor(predictions_dutch >= cutoffs["Dutch"])
  df_dutch["inv_predicted"] <- as.factor(inv_predictions_dutch >= cutoffs["Non_Dutch"])
  df_non_dutch["predicted"] <- as.factor(predictions_non_dutch >= cutoffs["Non_Dutch"])
  df_non_dutch["inv_predicted"] <- as.factor(inv_predictions_non_dutch >= cutoffs["Dutch"])

  joined_df <- bind_rows(df_dutch, df_non_dutch) %>%
    mutate(different = predicted != inv_predicted)

  list(sum(joined_df$different)/pop_size, joined_df)
}
```

## Setup
```{r}
original_n <- sum(df$accepted == "TRUE")

df_dutch <- filter(df, nationality == "Dutch")
df_non_dutch <- filter(df, nationality != "Dutch")

model <- naive_Bayes()
```

```{r}
cutoffs <- c(Dutch = 0.5, Non_Dutch = 0.5)

models <- list(Dutch = model %>% 
              fit(accepted ~ test_score + english_cert + extracurricular, df_dutch),
            Non_Dutch = model %>% 
              fit(accepted ~ test_score + english_cert + extracurricular, df_non_dutch))

predictions_df = predictions(df, models, cutoffs)

plot(filter(predictions_df, nationality == "Dutch") %>% select(predicted))
plot(filter(predictions_df, nationality == "Non_Dutch") %>% select(predicted))

result <- df_disc(predictions_df)

i <- 0
while (result$disc > 2) {
  
  if (result$n < original_n) {
    cutoffs <- adjust_fit(cutoffs, "up")
  } else {
    cutoffs <- adjust_fit(cutoffs, "down")
  }
  
  predictions_df = predictions(df, models, cutoffs)
  
  result <- df_disc(predictions_df)
  # print(result)
}

print(cutoffs)

plot(filter(predictions_df, nationality == "Dutch") %>% select(predicted))
plot(filter(predictions_df, nationality == "Non_Dutch") %>% select(predicted))
```

# Metrics
```{r}
print(group_fairness(predictions_df, nationality, predicted)[[1]])
print(causal_discrimination_joined_model(df, models, cutoffs)[[1]])
```

