---
title: "Pre-processing measures"
output:
  pdf_document: default
  html_notebook: default
---

# Imports

```{r}
library(fairmodels)
library(tidymodels)
library(rpart)
library(discrim)
source("../scripts/metrics_on_dataset.R")
```

## Data

```{r}
df <- read_rds("../data/selection.rds") %>%
  select(-rating, -gender)

df_test <- read_rds("../data/selection_test.rds") %>%
  select(-rating, -gender)
```

# Massaging

```{r}
nB_df <- df %>%
  mutate(accepted = as.factor(accepted),
         index = 1:1000)
fitted_Bayes_model <- naive_Bayes() %>%
  fit(accepted ~ nationality + test_score + english_cert +
        extracurricular,
      nB_df)
nB_predictions <- predict(fitted_Bayes_model, nB_df, type = "prob")
nB_df <- nB_df %>%
  mutate(prob_FALSE = nB_predictions[[".pred_FALSE"]],
         prob_TRUE = nB_predictions[[".pred_TRUE"]])
prob_true = sum(nB_df$accepted == "TRUE") / nrow(nB_df)
non_dutch_acceptance = nrow(
  filter(nB_df, accepted == "TRUE", nationality == "Non_Dutch")) /
  nrow(filter(nB_df, nationality == "Non_Dutch"))
print(non_dutch_acceptance)

while (non_dutch_acceptance < round(prob_true, 3)) {
  # Flip highest Non-Dutch
  highest_non_dutch <- nB_df %>%
    filter(accepted == "FALSE", nationality == "Non_Dutch") %>%
    arrange(desc(prob_TRUE)) %>%
    slice_head(n = 1) %>%
    select(index) %>%
    as.integer()
  
  # Flip lowest Dutch
  lowest_dutch <- nB_df %>%
    filter(accepted == "TRUE", nationality == "Dutch") %>%
    arrange(prob_TRUE) %>%
    slice_head(n = 1) %>%
    select(index) %>%
    as.integer()
  
  nB_df <- nB_df %>%
    mutate(
      accepted = replace(accepted, index == highest_non_dutch, "TRUE"),
      accepted = replace(accepted, index == lowest_dutch, "FALSE")
    )
  
  non_dutch_acceptance = nrow(filter(
    nB_df, accepted == "TRUE", nationality == "Non_Dutch")) /
    nrow(filter(nB_df, nationality == "Non_Dutch"))
  # print(non_dutch_acceptance)
}
nB_df <- nB_df %>%
  select(-index,-prob_FALSE,-prob_TRUE)

model <- decision_tree(mode = "classification")
massaging_results <- all_metrics(nB_df, model, df_test)
print_all_metrics("Massaging", massaging_results)
```
# Reweighting

```{r}
weights <- reweight(df$nationality, as.numeric(df$accepted))
weighted_model <- rpart(accepted ~ nationality + test_score + english_cert + 
                          extracurricular, df, weights)
weighted_df <- df_test %>%
  mutate(predicted = as.logical(predict(weighted_model, df_test)))
print("Reweighting")
print("Group fairness")
print(group_fairness(weighted_df, nationality, predicted)[[1]])
print("Causal Discrimination")
pop_size <- nrow(df)
# Flip nationalities
inverted_df <- df_test %>% 
  mutate(nationality = ifelse(nationality == "Dutch", "Non_Dutch", "Dutch"))
# Add prediction column
eval_df <- df_test %>%
  mutate(inverted_accepted = as.logical(predict(weighted_model, inverted_df)),
         different = accepted != inverted_accepted)
print(sum(eval_df$different)/pop_size)
print("Unawareness")
weighted_unaware_model <- rpart(accepted ~ test_score + english_cert + 
                                  extracurricular, df, weights)
weighted_unaware_df <- df_test %>%
  mutate(predicted = as.logical(predict(weighted_unaware_model, df_test)))
print(group_fairness(weighted_unaware_df, nationality, predicted)[[1]])
```

# Resampling

```{r}
resample_indexes <- resample(df$nationality, as.numeric(df$accepted))
resampled_df <- df[resample_indexes, ]
model <- decision_tree(mode = "classification")
resamping_results <- all_metrics(resampled_df, model, df_test)
print_all_metrics("Resampling", resamping_results)
```
